USE [BDD_PIZZERIA]
GO

/****** Object:  Table [dbo].[Article]    Script Date: 27/07/2023 14:10:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE Article(
	id_article int NOT NULL,
	nom varchar(50) NULL,
	prix int NULL,
	taille nchar(10) NULL,
 CONSTRAINT PK_Article PRIMARY KEY CLUSTERED 
(
	id_article ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

